### ISSUE TITLE
Button help pages

### ISSUE THREAD

**Issue by isuckatcodingdev35** [notLeaf/leaf-utils#1]
![Screenshot_20210828_234948](https://user-images.githubusercontent.com/87074223/131224694-8a97aad3-d678-45e8-8702-27ff313a59be.jpg)

Its shows that everytime i execute the command and interact with the reactions it makes my bot offline, idk why

**Comment by Lcxd65** [comment]
Bruh it literally said: node modules > discordjs and make sure your bot has perms. Btw there is the support server for the issues

**Comment by isuckatcodingdev35** [comment]
> Bruh it literally said: node modules > discordjs and make sure your bot has perms. Btw there is the support server for the issues

What do i do in discord.js node modules then, yes my bot has perms in my test server

**Comment by Lcxd65** [comment]
If it said that its a discordjs error, it didnt mention leaf-utils

**Comment by isuckatcodingdev35** [comment]
I fixed it lol
