### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by LNessy** [notLeaf/leaf-utils#4]
Unexpected token '?' in $djsEval[(async () => {
const { calculator } = require('leaf-utils');

await calculator({
			message: message,
			embed: {
				title: 'Calculator',
				color: 'RED',
				footer: 'calculator',
				timestamp: true,
			},
			disabledQuery: 'Calculator is disabled!',
			invalidQuery: 'The provided equation is invalid!',
			othersMessage: 'Only <@{{author}}> can use the buttons!',
		})

})()]

**Comment by rufy545** [comment]
Use aoi.js v5 dev. For other problems ask in his server
